# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sensei}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alex Scordellis"]
  s.date = %q{2009-10-22}
  s.default_executable = %q{sensei}
  s.description = %q{Sensei runs your dojo for you. You start with a single failing cucumber feature. As you make each feature pass, the next feature is brought into play. While you have failing features, you have the opportunity to write rspec specifications. Sensei will encourage you to refactor at appropriate moments, showing you your flog score as encouragement.}
  s.email = %q{alex.scordellis@gmail.com}
  s.executables = ["sensei"]
  s.files = [
    ".gitignore",
     "VERSION",
     "bin/sensei",
     "lib/sensei.rb",
     "lib/sensei/dojo.rb",
     "lib/sensei/git_tag_lister.rb",
     "lib/sensei/iteration_list.rb",
     "lib/sensei/repository.rb",
     "rakefile",
     "readme.markdown",
     "spec/sensei/git_tag_lister_spec.rb",
     "spec/sensei/iteration_list_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/alexscordellis/sensei}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Sensei runs your coding dojo for you.}
  s.test_files = [
    "spec/sensei/git_tag_lister_spec.rb",
     "spec/sensei/iteration_list_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rake>, [">= 0.8.7"])
      s.add_runtime_dependency(%q<rspec>, [">= 1.2.6"])
      s.add_runtime_dependency(%q<cucumber>, [">= 0.3.3"])
      s.add_runtime_dependency(%q<flog>, [">= 2.1.0"])
    else
      s.add_dependency(%q<rake>, [">= 0.8.7"])
      s.add_dependency(%q<rspec>, [">= 1.2.6"])
      s.add_dependency(%q<cucumber>, [">= 0.3.3"])
      s.add_dependency(%q<flog>, [">= 2.1.0"])
    end
  else
    s.add_dependency(%q<rake>, [">= 0.8.7"])
    s.add_dependency(%q<rspec>, [">= 1.2.6"])
    s.add_dependency(%q<cucumber>, [">= 0.3.3"])
    s.add_dependency(%q<flog>, [">= 2.1.0"])
  end
end

